### ISSUE TITLE
Form content recognized as spam

### ISSUE THREAD

**Issue by DonKoko** [aamodtgroup/frontity-contact-form-7#11]
I just heard from one of our users that our contact form doesnt work anymore.
I did some checks myself and found our that the API returns a spam message:

```json
{"into":"#wpcf7-f582-o1","status":"spam","message":"Beim Versuch, deine Mitteilung zu versenden, ist ein Fehler aufgetreten. Bitte versuche es sp\u00e4ter noch einmal.","posted_data_hash":""}
```

As you can see the status is `spam`. The message is the default CF7 message for "Sender's message failed to send". Any ideas why this could be happening? 
Form can be tested here: https://koenighaus-webshop-donkoko.vercel.app/kontakt/

Any idea what could be causing this. I am not aware of any updates done to cause this.

**Comment by kasperaamodt** [comment]
That has something to do with the email sender settings in WP. Nothing to do from this side.

**Comment by kasperaamodt** [comment]
I tested the form now, and it worked, so you have probably fixed the sender settings.

**Comment by DonKoko** [comment]
Thanks for answering Kasper. It was actually recaptcha causing the issue. It was not present in the form but someone had actually enabled it in CF7 settings.
