### ISSUE TITLE
Reset from is click on other section and goback

### ISSUE THREAD

**Issue by ferranpuigmar** [aamodtgroup/frontity-contact-form-7#12]
Hi, 
I have a problem when user interacts with form, and for example this throw errors, if user go to another section an go back to the form, this hase the same state, with the span errors, etc...

I tried to re render the component but it seems that the form component has a state in somewhere with the record of the fields status. It is possible? How Can I reset the form, once user click on subit button?

Thanks

**Comment by kasperaamodt** [comment]
When a user submits a form that is valid, the state is automatically reset. If the form has errors, the state is not reset, and if you leave and come back to the page, the fields still has the values and errors. This is not an error, it is so that you can continue on the form.

**Comment by kasperaamodt** [comment]
Hi,

This is now a feature. :)

[https://www.loom.com/share/d25f590779e74b00ae52b1cd97d0fb08](https://www.loom.com/share/d25f590779e74b00ae52b1cd97d0fb08)
