### ISSUE TITLE
Invalid input styling

### ISSUE THREAD

**Issue by brynzovskii** [aamodtgroup/frontity-contact-form-7#16]
At the moment the span with a error is added under the invalid input but no indication to the input itself. Let's say I need red outline instead of showing text under. The original form adds a `wpcf7-not-valid` class to the input and `area-invalid` set to true that can be used for styling as well. The package does not trigger the area-invalid attribute be set to true once the validation is required. 
![image](https://user-images.githubusercontent.com/11357106/157849210-ce043af4-3b3e-40e6-a7b8-85c8fd268af6.png)

`1.0.0-canary` version is used.

Any idea how to handle that? Thanks in advance.

**Comment by kasperaamodt** [comment]
I will check this out.
