### ISSUE TITLE
Validations not showing - After FIXED. 

### ISSUE THREAD

**Issue by abhalani648** [aamodtgroup/frontity-contact-form-7#18]
Hello,  

I just recently installed this plugin but when I run my project and checked the contact form so I got the error on the console area. 

Then I debugged your index.js file and fixed the code. Now all validations showing.

Please Comment on the below lines - 136 to 142
` /*let errorKey = item.into.replace(
        "span.wpcf7-form-control-wrap.",
        ""
    );
    if (errorKey) {
        invalidFieldsObj[errorKey] = item.message;
    }*/`

And add the below line
`invalidFieldsObj[item.field] = item.message;`

So the final code is 
` body.invalid_fields.forEach((item) => {
      /*let errorKey = item.into.replace(
          "span.wpcf7-form-control-wrap.",
          ""
      );
      if (errorKey) {
          invalidFieldsObj[errorKey] = item.message;
      }*/
      invalidFieldsObj[item.field] = item.message;
  });`

https://prnt.sc/Lnl8fl4ZJqZI

See on your demo website: 
https://prnt.sc/9f0y4uJeeHdW

So please update your index.js file. Thanks

**Comment by devellopah** [comment]
Hi @abhalani648
Looks like your fix works. Make a pull request, please.

**Comment by kasperaamodt** [comment]
Hi @abhalani648  could you please make a PR?

**Comment by abhalani648** [comment]
@kasperaamodt I have tried but permission was denied. Can you update by yourself? 

Thanks

**Comment by kasperaamodt** [comment]
This issues was fixed by PR #20.
