### ISSUE TITLE
Not possible to send mail

### ISSUE THREAD

**Issue by LowRadiance** [aamodtgroup/frontity-contact-form-7#6]
Hi there, your plugin works great so far, at least it does not throw any errors yet -)). But I cannot send emails. After filling all fields and pressing "send", it says "processing" and that's it...

Sending from the original WordPress site works.

**Comment by kasperaamodt** [comment]
Hi @LowRadiance,

Do you have a repo or a live site I can see?

**Comment by kasperaamodt** [comment]
This site has the latest plugin and package, and it works.

https://aamodtgroup.com/kontakt-oss/

**Comment by LowRadiance** [comment]
Hi @kasperaamodt ,

I suspect, that the Problem is the mandatory Consent Checkbox.

[https://release-software.de/kontakt/](url)

**Comment by kasperaamodt** [comment]
Hi @LowRadiance,

Aha, yes that's it, it does not have support for checkboxes yet. I've mainly focused on bug fixes from the earlier package. If you want to make the functionality you can just open a pr, if not I'm probably going to look at it in a few weeks.

**Comment by LowRadiance** [comment]
Hi @kasperaamodt ,

would love to make the changes, but I'm just a newbie on that Frontity or react stuff. I just did a few steps to see if that fits for me.

**Comment by jeffceriello** [comment]
Hi @kasperaamodt 

I have the same issue - the form doesn't send. I only get a Processing... text. In the console I get the error 

`Uncaught (in promise) TypeError: Failed to fetch` from `create-store.js`

I do not have any checkboxes. I only have text and textarea fields.

It's possible to check this on the live site https://wwtdigital.com/connect/

I have updated the module to the latest version 0.2.6 but that didn't fix the issue.

Here is the repo https://bitbucket.org/evildonkeylondon/wwt-frontend-frontity/src/pages/

Could you please advise how to fix it?

Thanks,
Jeff

**Comment by jeffceriello** [comment]
Hi, is the support for checkboxes now working? I have the acceptance checkbox needed for GDPR but the form does not send with it included. If I remove the acceptance/checkbox the form sends correctly. Without the checkbox support the module cannot be used unfortunately as there will be GDPR conflicts. Are there any advice on this matter? Thanks
