### ISSUE TITLE
Failed to fetch error - email not sending

### ISSUE THREAD

**Issue by jeffceriello** [aamodtgroup/frontity-contact-form-7#8]
Hi @kasperaamodt

I create a new ticket as the issue is actually different from the other post - the form just doesn't send. I only get a Processing... text. In the console I get the error

`Uncaught (in promise) TypeError: Failed to fetch` from `create-store.js`

I do not have any checkboxes. I only have text and textarea fields.

It's possible to check this on the live site `https://wwtdigital.com/connect/`

I have updated the module to the latest version 0.2.6 and also frontity to the most recent update but that didn't fix the issue.

Here is the repo `https://bitbucket.org/evildonkeylondon/wwt-frontend-frontity/src/pages/`

Could you please advise how to fix it?

Thanks,
Jeff

**Comment by kasperaamodt** [comment]
Hi,

From what I can see in the console, you have some cross origin problems:

https://ibb.co/GTHFxq1 (image)

**Comment by jeffceriello** [comment]
Hi @kasperaamodt 

Thanks for your reply. I could not see those issues in Chrome but I can see them in Safari.

The contact form 7 comes from the headless CMS, which is `wwtdigital-headless.com`, while the frontend is `wwtdigital.com`.

Isn't that the standard Frontity behaviour? That pulls data from the headless CMS? I'm a bit confused, sorry.

Are you able to point me in the right direction to resolve this issue?

Thanks!
Jeff

**Comment by kasperaamodt** [comment]
Hi @jeffceriello,

Cross origin is because of some security headers, I don't know very much about it. Try looking in the community forum. 

This may be a start:
https://community.frontity.org/t/cors-policy-issue/4898/4
